plugin:
  external_js_link:
    default: 'https://unpkg.com/react@18/umd/react.production.min.js'
    client: true
    description: 'Load a js script on valid routes'
  valid_routes:
    default: example|nested/route
    type: list
    description: 'Define your valid routes (prefixed with "/page")'
